apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-prod
  namespace: awesomeminecraft-com-prod
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`awesomeminecraft.com`) || Host(`www.awesomeminecraft.com`)
      services:
        - name: web
          port: 80
  tls:
    secretName: awesomeminecraft-com-prod-tls
